apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: callforge-frontend
  namespace: uat
spec:
  ingressClassName: nginx
  rules:
    - host: uat.callforge.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: callforge-frontend
                port:
                  number: 80